# Output and working directory (all other directories below, if not absolute, are relative to this one)
species: "anySpeciesName@edit"

# path or URL to sample sheet (TSV format, columns: sample, assembly); can be created by scripts/create_sampleSheet.sh --mode assembly
samples: "config/test_data.tsv"

params:
  threads: 1 #number of threads per rule
  abricate:
    name: "ncbi"
    path: "data/dbs" # path to ncbi resistance gene db (either from conda path/2/conda_env/db or custom)
    minid: 75 #minimum identity threshold
    mincov: 0 #minimum coverage threshold
  srst2:
    gene_db: "data/dbs/ResFinder.fasta"
    min_depth: 5
    max_divergence: 10
  ariba:
    gene_db: "data/dbs/ariba_card.prepareref"
  staramr:
    #empty, no options exposed
  amrfinder:
    gene_db: "data/dbs/amrfinder/latest"
  groot:
    gene_db: "data/dbs/groot-index-100"
    #empty as groot needs different db indexing by readlength and I haven't automated this in snakemake, not sure best approach.
  rgi:
    gene_db: "data/dbs/card/card.json"
  resfams:
    db: "data/dbs/Resfams-full.hmm"
  mykrobe:
    #todo
  resfinder:
    path: "data/dbs/resfinder"
  kmerresistance:
    amr_db: "data/dbs/resfinder/resfinder_kma"
    species_db: "data/dbs/resfinder/16S_species"
  srax:
     dbtype: "basic"
  amrplusplus:
    refdb: "data/dbs/megares/megares_drugs_database_v2.00.fasta"
    annots: "data/dbs/megares/megares_drugs_annotations_v2.00.csv" 
    resistome_tool: "data/dbs/megares/resistomeanalyzer/resistome"
    rarefaction_tool: "data/dbs/megares/rarefactionanalyzer/rarefaction"
    snp_tool: "data/dbs/megares/snpfinder/snpfinder"
